### ISSUE TITLE
[checkLinux.m] Error with gcc and g++

### ISSUE THREAD

**Issue by bigredbug47** [kopepod/ADCSF#1]
Hello,
I try to initialize your system. I did all installation requirements and everything is ok. But when I run checkLinux.m it return error with gcc and g++ version : **[error 3] please make sure gcc>= 4.4 and g++>=4.4 is installed.**
But I checked my gcc/g++ version, they was installed (version 4.8).
This is my system:
- Ubuntu 14.0
- Matlab 2017b
- opencv 2.4.10
- mexopencv (install from your folder LIB)
Thank you.

**Comment by sameema-tariq** [comment]
I am having the same issue. But my system has 
window 10
visual studio 2012
matlab 2017a
Kindly guide me if you resolved this issue
